sql = '''
SELECT 'DW_SF_FIN_ADDRESS' AS TABLE_NAME, COUNT(*) AS SOURCE_COUNT FROM ADDRESS
UNION ALL
SELECT 'DW_SF_FIN_ADDRESS_TYPE', COUNT(*) FROM ADDRESS_TYPE
UNION ALL
SELECT 'DW_SF_FIN_AGING_BUCKET', COUNT(*) FROM AGING_BUCKET
UNION ALL
SELECT 'DW_SF_FIN_APP_OBJECT_SECURITY', COUNT(*) FROM APPLICATION_OBJECT_SECURITY
UNION ALL
SELECT 'DW_SF_FIN_AP_AGING_TRANSACTION', COUNT(*) FROM AP_AGING_TRANSACTION
UNION ALL
SELECT 'DW_SF_FIN_AP_AGING_TRANS_STMT', COUNT(*) FROM AP_AGING_TRANS_STMT
UNION ALL
SELECT 'DW_SF_FIN_AP_SUMMARY', COUNT(*) FROM AP_SUMMARY
UNION ALL
SELECT 'DW_SF_FIN_AP_SUMMARY_REPORT', COUNT(*) FROM AP_SUMMARY_REPORT
UNION ALL
SELECT 'DW_SF_FIN_AR_AGING', COUNT(*) FROM AR_AGING
UNION ALL
SELECT 'DW_SF_FIN_AR_AGING_TRANSACTION', COUNT(*) FROM AR_AGING_TRANSACTION
UNION ALL
SELECT 'DW_SF_FIN_ATTACHMENT', COUNT(*) FROM ATTACHMENT
UNION ALL
SELECT 'DW_SF_FIN_BANK', COUNT(*) FROM BANK
UNION ALL
SELECT 'DW_SF_FIN_BANK_ACCOUNT', COUNT(*) FROM BANK_ACCOUNT
UNION ALL
SELECT 'DW_SF_FIN_BANK_ACCOUNT_LOT', COUNT(*) FROM BANK_ACCOUNT_LOT
UNION ALL
SELECT 'DW_SF_FIN_BANK_ADJUSTMENT', COUNT(*) FROM BANK_ADJUSTMENT
UNION ALL
SELECT 'DW_SF_FIN_BANK_ADJ_DISTRIBUTION', COUNT(*) FROM BANK_ADJUSTMENT_DISTRIBUTION
UNION ALL
SELECT 'DW_SF_FIN_BANK_ADJ_EXCHANGE_RATE', COUNT(*) FROM BANK_ADJUSTMENT_EXCHANGE_RATE
UNION ALL
SELECT 'DW_SF_FIN_BANK_BRANCH', COUNT(*) FROM BANK_BRANCH
UNION ALL
SELECT 'DW_SF_FIN_BANK_DEPOSIT', COUNT(*) FROM BANK_DEPOSIT
UNION ALL
SELECT 'DW_SF_FIN_BANK_RECONCILIATION', COUNT(*) FROM BANK_RECONCILIATION
UNION ALL
SELECT 'DW_SF_FIN_BANK_RECONCILIAT_DIST', COUNT(*) FROM BANK_RECONCILIATION_DIST
UNION ALL
SELECT 'DW_SF_FIN_BANK_TRANSACTION', COUNT(*) FROM BANK_TRANSACTION
UNION ALL
SELECT 'DW_SF_FIN_BANK_TRANSACTION_DETAIL', COUNT(*) FROM BANK_TRANSACTION_DETAIL
UNION ALL
SELECT 'DW_SF_FIN_BANK_TRANSACTION_TYPE', COUNT(*) FROM BANK_TRANSACTION_TYPE
UNION ALL
SELECT 'DW_SF_FIN_BANK_TRANS_XCHG_RATE', COUNT(*) FROM BANK_TRANS_EXCHANGE_RATE
UNION ALL
SELECT 'DW_SF_FIN_BUDGET', COUNT(*) FROM BUDGET
UNION ALL
SELECT 'DW_SF_FIN_BUDGET_GL_SEGMENT', COUNT(*) FROM BUDGET_GL_SEGMENT
UNION ALL
SELECT 'DW_SF_FIN_BUDGET_TYPE', COUNT(*) FROM BUDGET_TYPE
UNION ALL
SELECT 'DW_SF_FIN_CASH_RECEIPT', COUNT(*) FROM CASH_RECEIPT
UNION ALL
SELECT 'DW_SF_FIN_CASH_RECEIPT_CHARGEBACK', COUNT(*) FROM CASH_RECEIPT_CHARGEBACK
UNION ALL
SELECT 'DW_SF_FIN_CASH_RECEIPT_DIST', COUNT(*) FROM CASH_RECEIPT_DISTRIBUTION
UNION ALL
SELECT 'DW_SF_FIN_CASH_RECEIPT_PMT_XFER', COUNT(*) FROM CASH_RECEIPT_PMT_TRANSFER
UNION ALL
SELECT 'DW_SF_FIN_CASH_RECEIPT_XCHG_RATE', COUNT(*) FROM CASH_RECEIPT_EXCHANGE_RATE
UNION ALL
SELECT 'DW_SF_FIN_CHART_OF_ACCOUNT', COUNT(*) FROM CHART_OF_ACCOUNT
UNION ALL
SELECT 'DW_SF_FIN_CLEARING', COUNT(*) FROM CLEARING
UNION ALL
SELECT 'DW_SF_FIN_CLEARING_DETAIL', COUNT(*) FROM CLEARING_DETAIL
UNION ALL
SELECT 'DW_SF_FIN_COA_ACCOUNT_GROUP', COUNT(*) FROM COA_ACCOUNT_GROUP
UNION ALL
SELECT 'DW_SF_FIN_COA_SEGMENT', COUNT(*) FROM COA_SEGMENT
UNION ALL
SELECT 'DW_SF_FIN_COMMENTS', COUNT(*) FROM COMMENTS
UNION ALL
SELECT 'DW_SF_FIN_COMPANY', COUNT(*) FROM COMPANY
UNION ALL
SELECT 'DW_SF_FIN_COMPANY_CURRENCY', COUNT(*) FROM COMPANY_CURRENCY
UNION ALL
SELECT 'DW_SF_FIN_COMPANY_FISCAL_CALENDAR', COUNT(*) FROM COMPANY_FISCAL_CALENDAR
UNION ALL
SELECT 'DW_SF_FIN_COMPANY_FISCAL_PERIOD', COUNT(*) FROM COMPANY_FISCAL_PERIOD
UNION ALL
SELECT 'DW_SF_FIN_COMPANY_FISCAL_YEAR', COUNT(*) FROM COMPANY_FISCAL_YEAR
UNION ALL
SELECT 'DW_SF_FIN_COMPANY_PARAMETER', COUNT(*) FROM COMPANY_PARAMETER
UNION ALL
SELECT 'DW_SF_FIN_COMPANY_SEGMENT', COUNT(*) FROM COMPANY_SEGMENT
UNION ALL
SELECT 'DW_SF_FIN_COMPANY_SEGMENT_VALUE', COUNT(*) FROM COMPANY_SEGMENT_VALUE
UNION ALL
SELECT 'DW_SF_FIN_CONTACT', COUNT(*) FROM CONTACT
UNION ALL
SELECT 'DW_SF_FIN_CUSTOMER', COUNT(*) FROM CUSTOMER
UNION ALL
SELECT 'DW_SF_FIN_CUSTOMER_COMPANY', COUNT(*) FROM CUSTOMER_COMPANY
UNION ALL
SELECT 'DW_SF_FIN_CUSTOMER_GROUP', COUNT(*) FROM CUSTOMER_GROUP
UNION ALL
SELECT 'DW_SF_FIN_CUSTOMER_INVOICE', COUNT(*) FROM CUSTOMER_INVOICE
UNION ALL
SELECT 'DW_SF_FIN_CUST_INVOICE_XCHG_RATE', COUNT(*) FROM CUSTOMER_INVOICE_EXCHANGE_RATE
UNION ALL
SELECT 'DW_SF_FIN_DOCUMENT', COUNT(*) FROM DOCUMENT
UNION ALL
SELECT 'DW_SF_FIN_DOCUMENT_DETAIL', COUNT(*) FROM DOCUMENT_DETAIL
UNION ALL
SELECT 'DW_SF_FIN_DOCUMENT_DETAIL_SEGMENT', COUNT(*) FROM DOCUMENT_DETAIL_SEGMENT
UNION ALL
SELECT 'DW_SF_FIN_DOCUMENT_EXCHANGE_RATE', COUNT(*) FROM DOCUMENT_EXCHANGE_RATE
UNION ALL
SELECT 'DW_SF_FIN_FISCAL_PERIOD', COUNT(*) FROM FISCAL_PERIOD
UNION ALL
SELECT 'DW_SF_FIN_FS_CONTROL', COUNT(*) FROM FS_CONTROL
UNION ALL
SELECT 'DW_SF_FIN_FS_CONTROL_DETAIL', COUNT(*) FROM FS_CONTROL_DETAIL
UNION ALL
SELECT 'DW_SF_FIN_FS_CONTROL_REPORT', COUNT(*) FROM FS_CONTROL_REPORT
UNION ALL
SELECT 'DW_SF_FIN_FS_CTL_DETA_EXCLUDE', COUNT(*) FROM FS_CTL_DETA_EXCLUDE
UNION ALL
SELECT 'DW_SF_FIN_FS_REPORT_SECTION', COUNT(*) FROM FS_REPORT_SECTION
UNION ALL
SELECT 'DW_SF_FIN_FS_REPORT_SUBSECTION', COUNT(*) FROM FS_REPORT_SUBSECTION
UNION ALL
SELECT 'DW_SF_FIN_GL_SEGMENT', COUNT(*) FROM GL_SEGMENT
UNION ALL
SELECT 'DW_SF_FIN_GL_SEGMENT_DETAIL', COUNT(*) FROM GL_SEGMENT_DETAIL
UNION ALL
SELECT 'DW_SF_FIN_GL_SEGMENT_REPORT', COUNT(*) FROM GL_SEGMENT_REPORT
UNION ALL
SELECT 'DW_SF_FIN_GL_SEGMENT_SUMMARY_RPT', COUNT(*) FROM GL_SEGMENT_SUMMARY_REPORT
UNION ALL
SELECT 'DW_SF_FIN_INTFS_COMPANY_MAPPING', COUNT(*) FROM INTFS_COMPANY_MAPPING
UNION ALL
SELECT 'DW_SF_FIN_INVOICE', COUNT(*) FROM INVOICE
UNION ALL
SELECT 'DW_SF_FIN_INVOICE_DETAIL', COUNT(*) FROM INVOICE_DETAIL
UNION ALL
SELECT 'DW_SF_FIN_INVOICE_DISTRIBUTION', COUNT(*) FROM INVOICE_DISTRIBUTION
UNION ALL
SELECT 'DW_SF_FIN_INVOICE_DIST_SEGMENT', COUNT(*) FROM INVOICE_DISTRIBUTION_SEGMENT
UNION ALL
SELECT 'DW_SF_FIN_INVOICE_EXCHANGE_RATE', COUNT(*) FROM INVOICE_EXCHANGE_RATE
UNION ALL
SELECT 'DW_SF_FIN_INVOICE_PAY_REQUIREMENT', COUNT(*) FROM INVOICE_PAY_REQUIREMENT
UNION ALL
SELECT 'DW_SF_FIN_INVOICE_SPLIT_TERM', COUNT(*) FROM INVOICE_SPLIT_TERM
UNION ALL
SELECT 'DW_SF_FIN_IRO_GL_BOE_DETAILS', COUNT(*) FROM IRO_GL_BOE_DETAILS
UNION ALL
SELECT 'DW_SF_FIN_IRO_GL_BOE_HEADERS', COUNT(*) FROM IRO_GL_BOE_HEADERS
UNION ALL
SELECT 'DW_SF_FIN_IRO_PO_CLAIM_DETAILS', COUNT(*) FROM IRO_PO_CLAIM_DETAILS
UNION ALL
SELECT 'DW_SF_FIN_IRO_PO_CLAIM_HEADERS', COUNT(*) FROM IRO_PO_CLAIM_HEADERS
UNION ALL
SELECT 'DW_SF_FIN_IRO_PO_DETAILS', COUNT(*) FROM IRO_PO_DETAILS
UNION ALL
SELECT 'DW_SF_FIN_IRO_PO_HEADERS', COUNT(*) FROM IRO_PO_HEADERS
UNION ALL
SELECT 'DW_SF_FIN_IRO_PO_RECEIPT_DETAILS', COUNT(*) FROM IRO_PO_RECEIPT_DETAILS
UNION ALL
SELECT 'DW_SF_FIN_IRO_PO_RECEIPT_HEADERS', COUNT(*) FROM IRO_PO_RECEIPT_HEADERS
UNION ALL
SELECT 'DW_SF_FIN_ISO_COUNTRY', COUNT(*) FROM ISO_COUNTRY
UNION ALL
SELECT 'DW_SF_FIN_PAYMENT_METHOD', COUNT(*) FROM PAYMENT_METHOD
UNION ALL
SELECT 'DW_SF_FIN_PAYMENT_TERM', COUNT(*) FROM PAYMENT_TERM
UNION ALL
SELECT 'DW_SF_FIN_POSTING_ACCOUNT', COUNT(*) FROM POSTING_ACCOUNT
UNION ALL
SELECT 'DW_SF_FIN_POSTING_ACT_SEGMENT_DFT', COUNT(*) FROM POSTING_ACCOUNT_SEGMENT_DFT
UNION ALL
SELECT 'DW_SF_FIN_PO_DETAIL', COUNT(*) FROM PO_DETAIL
UNION ALL
SELECT 'DW_SF_FIN_PURCHASE_ORDER', COUNT(*) FROM PURCHASE_ORDER
UNION ALL
SELECT 'DW_SF_FIN_REASON', COUNT(*) FROM REASON
UNION ALL
SELECT 'DW_SF_FIN_RECEIPT', COUNT(*) FROM RECEIPT
UNION ALL
SELECT 'DW_SF_FIN_RECEIPT_DETAIL', COUNT(*) FROM RECEIPT_DETAIL
UNION ALL
SELECT 'DW_SF_FIN_SECURITY_ROLE', COUNT(*) FROM SECURITY_ROLE
UNION ALL
SELECT 'DW_SF_FIN_SECURITY_ROLE_OBJECT', COUNT(*) FROM SECURITY_ROLE_OBJECT
UNION ALL
SELECT 'DW_SF_FIN_SEGMENT', COUNT(*) FROM SEGMENT
UNION ALL
SELECT 'DW_SF_FIN_SEGMENT_GROUP_TYPE', COUNT(*) FROM SEGMENT_GROUP_TYPE
UNION ALL
SELECT 'DW_SF_FIN_SEGMENT_VALUE', COUNT(*) FROM SEGMENT_VALUE
UNION ALL
SELECT 'DW_SF_FIN_SGMT_GRP_TYPEVAL_SEGVAL', COUNT(*) FROM SEGMENT_GROUP_TYPEVAL_SEGVAL
UNION ALL
SELECT 'DW_SF_FIN_SGMT_GRP_TYPE_VALUE', COUNT(*) FROM SEGMENT_GROUP_TYPE_VALUE
UNION ALL
SELECT 'DW_SF_FIN_SPLIT_PAYMENT_TERM', COUNT(*) FROM SPLIT_PAYMENT_TERM
UNION ALL
SELECT 'DW_SF_FIN_STATE_PROVINCE', COUNT(*) FROM STATE_PROVINCE
UNION ALL
SELECT 'DW_SF_FIN_TAX', COUNT(*) FROM TAX
UNION ALL
SELECT 'DW_SF_FIN_UNMATCH_RECEIPT_DETAIL', COUNT(*) FROM UNMATCHED_RECEIPT_DETAIL
UNION ALL
SELECT 'DW_SF_FIN_USER_COMPANY', COUNT(*) FROM USER_COMPANY
UNION ALL
SELECT 'DW_SF_FIN_USER_COMPANY_DETAIL', COUNT(*) FROM USER_COMPANY_DETAIL
UNION ALL
SELECT 'DW_SF_FIN_USER_PROFILE', COUNT(*) FROM USER_PROFILE
UNION ALL
SELECT 'DW_SF_FIN_VENDOR', COUNT(*) FROM VENDOR
UNION ALL
SELECT 'DW_SF_FIN_VENDOR_COMPANY', COUNT(*) FROM VENDOR_COMPANY
UNION ALL
SELECT 'DW_SF_FIN_VENDOR_GROUP', COUNT(*) FROM VENDOR_GROUP
 '''